server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DevDojo?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
